% demo script to make a 3D surface plot using from a contour data file
% generated by the Perple_X program WERAMI, for data file format see 
% www.perplex.ethz.ch/perplex/special/README_WERAMI_GRID_FORMAT.txt

clear all;clf;

%open werami ascii file

[x,y,d,xname,yname,ok] = get_perple_x_file;
%                                     3D plot with phong lighting
figure(1);
surf(x,y,d);light;shading interp;lighting phong;axis tight;xlabel(xname);ylabel(yname); 
%                                     to add colorbar uncomment:
%colorbar;





